# configuration file for pvcast

# general configuration
general:
  weather: 'scrapper'
  location:
    latitude: 52.35845515630293
    longitude: 4.88115070391368
    altitude: 0

plant:
  # PVSystem level. Each entry in list represents one ModelChain(PVSystem) object.
  - name: 'EastWest'
    inverter: 'SolarEdge_Technologies_Ltd___SE4000__240V_'
    microinverter: false
    arrays:
      # Array level. Each entry in list represents one Array object.
      - name: 'East'
        tilt: 30
        azimuth: 90
        modules_per_string: 4
        strings: 1
        module: 'Trina_Solar_TSM_330DD14A_II_'
      - name: 'West'
        tilt: 30
        azimuth: 270
        modules_per_string: 8
        strings: 1
        module: 'Trina_Solar_TSM_330DD14A_II_'
