---
blank_issues_enabled: true
contact_links:
  - name: ❓ Ask a Question
    url: https://https://github.com/Open-HEMS/pvcast/discussions/new/choose
    about: We use GitHub issues for tracking bugs / feature requests, check discussions for questions.
