name: Codecov
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.1.1
        with:
          lfs: "true"
      - name: Set up Python 3.12.1
        uses: actions/setup-python@v4.8.0
        with:
          python-version: "3.12.1"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run unit tests and collect coverage
        run: pytest --cov=pvcast tests/ -n auto
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
