name: Workflow for Codecov
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'dev'        
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run tests and collect coverage
        run: pytest --cov src
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
