---
name: Testing

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.12"

jobs:
  pytest:
    name: pytest on Python $DEFAULT_PYTHON
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: 🏗 Set up Poetry
        run: pip install poetry
      - name: 🏗 Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "pip"
      - name: 🏗 Install workflow dependencies
        run: poetry config virtualenvs.create false
      - name: 🏗 Install Python dependencies
        run: poetry install --no-interaction --no-ansi
      - name: 🚀 Run pytest
        run: pytest -n auto --cov pvcast tests
      - name: ⬆️ Upload coverage artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: coverage-${{ env.DEFAULT_PYTHON }}
          path: .coverage

  coverage:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: ⬇️ Download coverage data
        uses: actions/download-artifact@v4.1.1
      - name: 🏗 Set up Poetry
        run: pip install poetry
      - name: 🏗 Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: "pip"
      - name: 🏗 Install workflow dependencies
        run: poetry config virtualenvs.create false
      - name: 🏗 Install Python dependencies
        run: poetry install --no-interaction --no-ansi
      - name: 🚀 Process coverage results
        run: |
          coverage combine coverage*/.coverage*
          coverage xml -i
      - name: 🚀 Upload coverage report
        uses: codecov/codecov-action@v3.1.4
